spring:
  application:
    name: movie-service
  config:
      import: optional:configserver:http://localhost:8888
  cloud:
      config:
        fail-fast: true
  datasource:
    url: jdbc:h2:mem:filmedb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

